# Generated by Django 2.1.5 on 2019-09-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('stack_it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='access_permissions',
            field=models.ManyToManyField(help_text='Which permissions allow user to see the object', to='auth.Permission', verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Does your object needs specific access?', verbose_name='Is Public'),
        ),
    ]
