# Generated by Django 2.1.5 on 2019-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('stack_it', '0002_auto_20190903_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='access_permissions',
        ),
        migrations.AddField(
            model_name='page',
            name='allowed_groups',
            field=models.ManyToManyField(help_text='Which groups are allowed to see the object', to='auth.Group', verbose_name='Groups'),
        ),
    ]
