# Generated by Django 2.1.5 on 2019-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0004_auto_20191021_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='Login required'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='stack-it/images', verbose_name='Image'),
        ),
    ]
