# Generated by Django 2.1.5 on 2019-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='auto_slug_en_us',
            field=models.BooleanField(default=True, help_text="When set, your slug will automatically be updated from field define in class's SLUGIFY_FROM", verbose_name='Auto Slug'),
        ),
        migrations.AddField(
            model_name='page',
            name='auto_slug_fr',
            field=models.BooleanField(default=True, help_text="When set, your slug will automatically be updated from field define in class's SLUGIFY_FROM", verbose_name='Auto Slug'),
        ),
        migrations.AddField(
            model_name='page',
            name='ref_full_path_en_us',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Denormalized full path'),
        ),
        migrations.AddField(
            model_name='page',
            name='ref_full_path_fr',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Denormalized full path'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_en_us',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_fr',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en_us',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
    ]
