# Generated by Django 2.1.5 on 2019-01-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menu',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_removed',
        ),
    ]
