# Generated by Django 2.1.5 on 2019-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(default='', max_length=250, verbose_name='Meta Description'),
            preserve_default=False,
        ),

    ]
