# Generated by Django 2.1.7 on 2019-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='auto_slug_en_us',
            new_name='auto_slug_en',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='ref_full_path_en_us',
            new_name='ref_full_path_en',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='slug_en_us',
            new_name='slug_en',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_en_us',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='textpagecontent',
            old_name='value_en_us',
            new_name='value_en',
        ),
        migrations.RenameField(
            model_name='texttemplatecontent',
            old_name='value_en_us',
            new_name='value_en',
        ),
        migrations.AlterField(
            model_name='image',
            name='folder',
            field=models.CharField(choices=[('articles', 'articles'), ('residences', 'residences'), ('services', 'services'), ('equipe', 'equipe')], default='articles', max_length=50, verbose_name='Folder'),
        ),
    ]
