# Generated by Django 2.1.5 on 2019-07-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0002_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_fr',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(default='', max_length=250, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='ref_full_path',
            field=models.SlugField(editable=False, max_length=500, verbose_name='Denormalized full path'),
        ),
        migrations.AlterField(
            model_name='page',
            name='ref_full_path_en',
            field=models.SlugField(editable=False, max_length=500, null=True, verbose_name='Denormalized full path'),
        ),
        migrations.AlterField(
            model_name='page',
            name='ref_full_path_fr',
            field=models.SlugField(editable=False, max_length=500, null=True, verbose_name='Denormalized full path'),
        ),
    ]
