# Generated by Django 2.1.5 on 2019-01-17 15:09

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0002_auto_20190117_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en_us',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
    ]
