# Generated by Django 2.1.7 on 2019-04-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0002_auto_20190412_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='auto_slug_en_us',
            new_name='auto_slug_en',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='ref_full_path_en_us',
            new_name='ref_full_path_en',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='slug_en_us',
            new_name='slug_en',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_en_us',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='textpagecontent',
            old_name='value_en_us',
            new_name='value_en',
        ),
    ]
