# Generated by Django 2.2.3 on 2019-08-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0003_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='folder',
            field=models.CharField(choices=[('articles', 'articles'), ('residences', 'residences'), ('services', 'services'), ('equipe', 'equipe')], default='articles', max_length=50, verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
