# Generated by Django 2.1.5 on 2019-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0003_auto_20190413_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='auto_slug_en',
            new_name='auto_slug_en_us',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='ref_full_path_en',
            new_name='ref_full_path_en_us',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='slug_en',
            new_name='slug_en_us',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_en',
            new_name='title_en_us',
        ),
        migrations.RenameField(
            model_name='textpagecontent',
            old_name='value_en',
            new_name='value_en_us',
        ),
        migrations.AlterField(
            model_name='image',
            name='folder',
            field=models.CharField(choices=[('folder', 'folder')], default='folder', max_length=50, verbose_name='Folder'),
        ),
    ]
