# Generated by Django 2.1.5 on 2019-01-17 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stack_it', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(max_length=50, verbose_name='Key')),
                ('content_type', models.CharField(choices=[('meta', 'Meta content'), ('value', 'Standard content')], default='value', max_length=50, verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'PageContent',
                'verbose_name_plural': 'PageContents',
            },
        ),
        migrations.CreateModel(
            name='ImagePageContent',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stack_it.PageContent')),
                ('ref_image', models.ImageField(upload_to='', verbose_name='Image')),
                ('ref_alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternative text')),
                ('size', models.CharField(default='800x600', max_length=50, verbose_name='Size')),
                ('value', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack_it.Image', verbose_name='Image instance')),
            ],
            options={
                'abstract': False,
            },
            bases=('stack_it.pagecontent', models.Model),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_stack_it.pagecontent_set+', to='contenttypes.ContentType'),
        ),
    ]
