# Generated by Django 2.1.5 on 2019-01-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0005_auto_20190117_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepagecontent',
            name='value',
        ),
    ]
