# Generated by Django 2.2.3 on 2019-08-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0005_page_main_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_images', to='stack_it.Image', verbose_name='Meta Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(default='', help_text='keep this under 60 characters for best optimisation', max_length=250, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_en',
            field=models.CharField(default='', help_text='keep this under 60 characters for best optimisation', max_length=250, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_fr',
            field=models.CharField(default='', help_text='keep this under 60 characters for best optimisation', max_length=250, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.TextField(blank=True, help_text='Facebook description less than 300 characters', verbose_name='Facebook Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description_en',
            field=models.TextField(blank=True, help_text='Facebook description less than 300 characters', null=True, verbose_name='Facebook Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description_fr',
            field=models.TextField(blank=True, help_text='Facebook description less than 300 characters', null=True, verbose_name='Facebook Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='must be at least 1200x630px', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='od_images', to='stack_it.Image', verbose_name='Facebook Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, help_text='Keep it under 55 characters for best optimisation', max_length=100, verbose_name='Facebook Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Keep it under 55 characters for best optimisation', max_length=100, null=True, verbose_name='Facebook Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title_fr',
            field=models.CharField(blank=True, help_text='Keep it under 55 characters for best optimisation', max_length=100, null=True, verbose_name='Facebook Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='tw_description',
            field=models.TextField(blank=True, help_text='Twitter description less than 200 characters', verbose_name='Twitter Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='tw_description_en',
            field=models.TextField(blank=True, help_text='Twitter description less than 200 characters', null=True, verbose_name='Twitter Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='tw_description_fr',
            field=models.TextField(blank=True, help_text='Twitter description less than 200 characters', null=True, verbose_name='Twitter Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='tw_image',
            field=models.ForeignKey(blank=True, help_text='must be at least 120x120px', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tw_images', to='stack_it.Image', verbose_name='Twitter Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='tw_title',
            field=models.CharField(blank=True, help_text='Keep this under 70 characters for best optimisation', max_length=100, verbose_name='Twitter Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='tw_title_en',
            field=models.CharField(blank=True, help_text='Keep this under 70 characters for best optimisation', max_length=100, null=True, verbose_name='Twitter Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='tw_title_fr',
            field=models.CharField(blank=True, help_text='Keep this under 70 characters for best optimisation', max_length=100, null=True, verbose_name='Twitter Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(default='', help_text='keep this under 160 characters for best optimisation', max_length=250, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_en',
            field=models.CharField(default='', help_text='keep this under 160 characters for best optimisation', max_length=250, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_fr',
            field=models.CharField(default='', help_text='keep this under 160 characters for best optimisation', max_length=250, null=True, verbose_name='Meta Description'),
        ),
    ]
