# Generated by Django 2.1.5 on 2019-01-17 17:37

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0006_remove_imagepagecontent_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepagecontent',
            name='value',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
