# Generated by Django 2.2.3 on 2019-08-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0006_auto_20190814_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='main_site',
            field=models.ForeignKey(blank=True, help_text='In case the page is available on multiple websites, choose which one is to be considered as the main one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_as_main_site', to='sites.Site', verbose_name='Main Site'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.TextField(default='', help_text='keep this under 60 characters for best optimisation', verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title_en',
            field=models.TextField(default='', help_text='keep this under 60 characters for best optimisation', null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title_fr',
            field=models.TextField(default='', help_text='keep this under 60 characters for best optimisation', null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sites',
            field=models.ManyToManyField(help_text='This page will be available for each of those websites', to='sites.Site', verbose_name='Site'),
        ),
    ]
