# Generated by Django 2.2.3 on 2019-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0007_auto_20190814_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='priority',
            field=models.FloatField(default=0.5, verbose_name='Page priority for indexation'),
        ),
    ]
