# Generated by Django 2.1.5 on 2019-01-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0007_imagepagecontent_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepagecontent',
            name='value',
        ),
    ]
