# Generated by Django 2.1.5 on 2019-01-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0008_remove_imagepagecontent_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPageContent',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stack_it.PageContent')),
                ('instance_id', models.IntegerField(null=True, verbose_name='Object id')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model Name')),
            ],
            options={
                'verbose_name': 'Model Page Content',
                'verbose_name_plural': 'Model Page Contents',
            },
            bases=('stack_it.pagecontent', models.Model),
        ),
        migrations.CreateModel(
            name='PagePageContent',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stack_it.PageContent')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_contents', to='stack_it.Page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page Page Content',
                'verbose_name_plural': 'Page Page Contents',
            },
            bases=('stack_it.pagecontent', models.Model),
        ),
        migrations.CreateModel(
            name='TextPageContent',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stack_it.PageContent')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Text Page Content',
                'verbose_name_plural': 'Text Page Contents',
            },
            bases=('stack_it.pagecontent', models.Model),
        ),
        migrations.AlterModelOptions(
            name='imagepagecontent',
            options={'verbose_name': 'Image Page Content', 'verbose_name_plural': 'Image Page Contents'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Page Content', 'verbose_name_plural': 'Page Contents'},
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='stack_it.Page', verbose_name='Page'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together={('page', 'key')},
        ),
    ]
