# Generated by Django 2.2.3 on 2019-08-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0008_page_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='changefreq',
            field=models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='monthly', max_length=50, verbose_name='Page change frequency'),
        ),
    ]
