# Generated by Django 2.2.3 on 2019-08-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_it', '0009_page_changefreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update date'),
        ),
    ]
