# Generated by Django 2.1.5 on 2019-01-18 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stack_it.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stack_it', '0010_auto_20190118_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(max_length=50, verbose_name='Key')),
                ('content_type', models.CharField(choices=[('meta', 'Meta content'), ('value', 'Standard content')], default='value', max_length=50, verbose_name='Content Type')),
                ('path', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Template',
            },
        ),
        migrations.AlterModelOptions(
            name='modelpagecontent',
            options={'verbose_name': 'Related Model Page Content', 'verbose_name_plural': 'Related Model Page Contents'},
        ),
        migrations.AlterModelOptions(
            name='pagepagecontent',
            options={'verbose_name': 'Related Page Page Content', 'verbose_name_plural': 'Related Page Page Contents'},
        ),
        migrations.AlterField(
            model_name='pagepagecontent',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pagepagecontent', to='stack_it.Page', verbose_name='Page'),
        ),
        migrations.CreateModel(
            name='ImageTemplateContent',
            fields=[
                ('templatecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stack_it.TemplateContent')),
                ('ref_image', models.ImageField(upload_to='', verbose_name='Image')),
                ('ref_alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternative text')),
                ('size', models.CharField(default='800x600', max_length=50, validators=[stack_it.utils.validators.validate_image_size], verbose_name='Size')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack_it.Image', verbose_name='Image instance')),
            ],
            options={
                'verbose_name': 'Image Template Content',
                'verbose_name_plural': 'Image Template Contents',
            },
            bases=('stack_it.templatecontent', models.Model),
        ),
        migrations.CreateModel(
            name='ModelTemplateContent',
            fields=[
                ('templatecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stack_it.TemplateContent')),
                ('instance_id', models.IntegerField(null=True, verbose_name='Object id')),
                ('model_name', models.CharField(max_length=50, validators=[stack_it.utils.validators.validate_model_name], verbose_name='Model Name')),
            ],
            options={
                'verbose_name': 'Related Model Template Content',
                'verbose_name_plural': 'Related Model Template Contents',
            },
            bases=('stack_it.templatecontent', models.Model),
        ),
        migrations.CreateModel(
            name='PageTemplateContent',
            fields=[
                ('templatecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stack_it.TemplateContent')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pagetemplatecontent', to='stack_it.Page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Related Page Template Content',
                'verbose_name_plural': 'Related Page Template Contents',
            },
            bases=('stack_it.templatecontent', models.Model),
        ),
        migrations.CreateModel(
            name='TextTemplateContent',
            fields=[
                ('templatecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stack_it.TemplateContent')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Text Template Content',
                'verbose_name_plural': 'Text Template Contents',
            },
            bases=('stack_it.templatecontent', models.Model),
        ),
        migrations.AddField(
            model_name='templatecontent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_stack_it.templatecontent_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='templatecontent',
            unique_together={('path', 'key')},
        ),
    ]
